### ISSUE TITLE
tests fail on malformed eml file

### ISSUE THREAD

**Issue by SteveClement** [MISP/mail_to_misp_test#4]
Copying `tests/mails/attachment_forward.eml tests/mails/simple_forward.eml` makes it work. Something is fishy with simple_forward.eml

```
$ poetry run nosetests --with-coverage --cover-package=mail2misp tests/tests.py
.........
Name                      Stmts   Miss  Cover
---------------------------------------------
mail2misp/__init__.py         3      0   100%
mail2misp/hashmarker.py       3      0   100%
mail2misp/mail2misp.py      323     66    80%
mail2misp/urlmarker.py        5      0   100%
---------------------------------------------
TOTAL                       334     66    80%
----------------------------------------------------------------------
Ran 9 tests in 0.603s

OK
```

pymisp/tools/emailobject.py L53 -> len(eml) is 0.

Failure:
```
$ mail_to_misp> poetry run nosetests --with-coverage --cover-package=mail2misp tests/tests.py
..E......
======================================================================
ERROR: test_forward (mail_to_misp.tests.tests.TestMailToMISP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/steve/Desktop/code/MISP_Main/mail_to_misp/tests/tests.py", line 40, in test_forward
    self.mail2misp.process_email_body()
  File "/home/steve/Desktop/code/MISP_Main/mail_to_misp/./mail2misp/mail2misp.py", line 194, in process_email_body
    self._find_inline_forward()
  File "/home/steve/Desktop/code/MISP_Main/mail_to_misp/./mail2misp/mail2misp.py", line 93, in _find_inline_forward
    return self.forwarded_email(pseudofile=BytesIO(fw_email.encode()))
  File "/home/steve/Desktop/code/MISP_Main/mail_to_misp/./mail2misp/mail2misp.py", line 141, in forwarded_email
    email_object = EMailObject(pseudofile=pseudofile, attach_original_mail=True, standalone=False)
  File "/home/steve/.cache/pypoetry/virtualenvs/mail2misp-CBIT9vqK-py3.8/lib/python3.8/site-packages/pymisp/tools/emailobject.py", line 43, in __init__
    self.email = self.parse_email()
  File "/home/steve/.cache/pypoetry/virtualenvs/mail2misp-CBIT9vqK-py3.8/lib/python3.8/site-packages/pymisp/tools/emailobject.py", line 87, in parse_email
    raise PyMISPNotImplementedYet("EmailObject does not know how to decode data passed to it. Object may not be an email. If this is an email please submit it as an issue to PyMISP so we can add support.")
pymisp.exceptions.PyMISPNotImplementedYet: EmailObject does not know how to decode data passed to it. Object may not be an email. If this is an email please submit it as an issue to PyMISP so we can add support.
-------------------- >> begin captured stdout << ---------------------
Entering parse_email
got here
0

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
pymisp: DEBUG: Email not in standard .eml format. Attempting to decode email from other formats.
--------------------- >> end captured logging << ---------------------

Name                      Stmts   Miss  Cover
---------------------------------------------
mail2misp/__init__.py         3      0   100%
mail2misp/hashmarker.py       3      0   100%
mail2misp/mail2misp.py      323     66    80%
mail2misp/urlmarker.py        5      0   100%
---------------------------------------------
TOTAL                       334     66    80%
----------------------------------------------------------------------
Ran 9 tests in 0.478s

FAILED (errors=1)
```

**Comment by Rafiot** [comment]
This will be fixed by PyMISP 2.4.148.1. 

No idea why it wasn't failing before, but the reason is that the mail parsing library in python doesn't recognize a mail if the blob starts with a newline. PyMISP 2.4.148.1+ triggers a `strip` before parsing, which solves the problem. 

The dependencies in mail_to_misp will be updated accordingly in a few min.
